DROP TABLE security_role IF EXISTS;

CREATE TABLE security_role(
id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
name VARCHAR(50) DEFAULT NULL,
PRIMARY KEY (id));


DROP TABLE user IF EXISTS;

CREATE TABLE user
(id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, 
first_name VARCHAR(45) DEFAULT NULL, 
family_name VARCHAR(45) DEFAULT NULL, 
dob DATE DEFAULT NULL, 
password VARCHAR(45) NOT NULL, 
username VARCHAR(45) NOT NULL, 
confirm_password VARCHAR(45) NOT NULL, 
active TINYINT NOT NULL,
PRIMARY KEY (id));
ALTER TABLE user ADD CONSTRAINT userUnique UNIQUE(username);

DROP TABLE user_security_role IF EXISTS;

CREATE TABLE user_security_role
(user_id INT NOT NULL,
security_role_id INT NOT NULL ,
PRIMARY KEY (user_id, security_role_id));

CREATE INDEX security_role_id ON user_security_role (security_role_id ASC);
ALTER TABLE user_security_role ADD CONSTRAINT user_security_role_ibfk_1 FOREIGN KEY(user_id)
REFERENCES user(id);
ALTER TABLE user_security_role ADD CONSTRAINT user_security_role_ibfk_2 FOREIGN KEY(security_role_id)
REFERENCES security_role(id);
 
 